#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app_name + '-env'
  annotations:
    #! tell kapp to redeploy deployment on change
    #! https://github.com/vmware-tanzu/carvel-kapp/blob/develop/docs/diff.md#versioned-resources
    kapp.k14s.io/versioned: ''
type: Opaque
stringData: #@ data.values.env_vars
